"""Accounting provider protocol used by export and reconciliation services."""
from typing import Protocol,Any
class AccountingProvider(Protocol):
 def company(self,token:str)->dict[str,Any]:...
 def references(self,kind:str)->list[dict[str,Any]]:...
 def create_purchase(self,payload:dict[str,Any],dedupe_key:str)->dict[str,Any]:...
 def get_purchase(self,provider_id:str)->dict[str,Any]:...
