"""Tax audit PDF rendering."""

import io

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table


def generate_tax_audit_pdf(summary: dict) -> bytes:
    out = io.BytesIO()
    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(out, pagesize=A4, title="ReceiptLens Tax Audit")
    rows = [["Category", "Count", "Total"]] + [
        [x["tax_category"], x["count"], f"{x['total']:.2f}"] for x in summary["by_category"]
    ]
    doc.build(
        [
            Paragraph(f"Tax Audit {summary['year']} ({summary['locale']})", styles["Title"]),
            Spacer(1, 12),
            Table(rows),
            Spacer(1, 12),
            Paragraph(f"Grand total: {summary['grand_total']:.2f}", styles["Heading2"]),
            Paragraph(
                "Generated by ReceiptLens. Review with a qualified tax professional.",
                styles["BodyText"],
            ),
        ]
    )
    return out.getvalue()
